### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Shawzborne** [notbenoit/tvOS-Twitch#1]
![screen shot 2015-11-09 at 12 00 35 pm](https://cloud.githubusercontent.com/assets/5931778/11040299/86900376-86d9-11e5-8113-d4680ff1eb66.png)

**Comment by notbenoit** [comment]
Did you clone the submodules too ?

**Comment by Shawzborne** [comment]
How do you do that?

**Comment by notbenoit** [comment]
There's a readme file for that.
Simply `git clone --recursive git@github.com:notbenoit/tvOS-Twitch.git`or if you already cloned the repo `git submodule update --init --recursive`
