### ISSUE TITLE
StreamsViewController can not play streaming

### ISSUE THREAD

**Issue by OptimusKe** [notbenoit/tvOS-Twitch#2]
StreamsViewController can not play streaming, I tapped cell then nothing happended,
but GamesViewController works. could you fix it?  thanks.

**Comment by notbenoit** [comment]
Should be fixed now, thanks for raising the issue (I did not even try this feature when I added the new tab...) 👍

**Comment by OptimusKe** [comment]
Nice Job!  Thank you
